name: Run Tests

on:
  push:
    branches: [ master, main, vibecode, setup-github-actions ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov pytest-timeout
    
    - name: Install package in development mode
      run: |
        pip install -e .
    
    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=agents --cov=mcp --cov=cli --cov=utils \
               --cov-report=xml --cov-report=term \
               -k "not integration and not e2e and not tunnel and not requires_api_key" \
               --timeout=60
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Run integration tests (without API keys)
      run: |
        pytest tests/ -v -k "integration" -m "not requires_api_key" \
               --timeout=120 || true
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.13'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
    
    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check . --diff || true
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff . || true
    
    - name: Type checking with mypy
      run: |
        mypy . --ignore-missing-imports || true

  test-mcp-server:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test MCP server startup
      run: |
        # Try to start MCP server in stdio mode (doesn't require API key)
        echo "Testing MCP server in stdio mode..."
        
        # Create a simple test to verify the module can be imported
        cat > test_import.py << 'EOF'
        import sys
        sys.path.insert(0, '.')
        try:
            from mcp.vibeteam_mcp_server import main_console
            print('✅ MCP server module imported successfully')
        except Exception as e:
            print(f'❌ Failed to import MCP server: {e}')
            sys.exit(1)
        
        # Note: software_engineer_server was removed, only stdio mode is supported
        print('✅ Import tests completed successfully')
        EOF
        
        python test_import.py
      env:
        MCP_MODE: stdio
        PYTHONPATH: ${{ github.workspace }}